title: Shri
description: a random guy trying to do something 

markdown: kramdown
kramdown:
  math_engine: mathjax

style:
  main: style.css
  content: content.css

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
